/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Fish: typeof import('./src/components/Fish/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Friend: typeof import('./src/components/Friend/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Image: typeof import('./src/components/Image/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Util: typeof import('./src/components/util/index.vue')['default']
    Waves: typeof import('./src/components/Waves/index.vue')['default']
  }
}
